### ISSUE TITLE
error on pip install -r requirements.txt

### ISSUE THREAD

**Issue by quasarblue** [nemtech/nem2-docs#1]
Hi,
on windows, git bash, python 3.6.4, pip 9.0.3
on the directory of git clone for nem2docs,
running pip install I receive this 

Collecting sphinxcontrib-examplecode==0.1.0 (from -r requirements.txt (line 14))
  Using cached sphinxcontrib-examplecode-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mario\appdata\local\programs\python\python36-32\lib\site-pa                         ckages\setuptools\__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "c:\users\mario\appdata\local\programs\python\python36-32\lib\site-pa                         ckages\setuptools\extern\__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "c:\users\mario\appdata\local\programs\python\python36-32\lib\site-pa                         ckages\pkg_resources\__init__.py", line 3017, in <module>
        @_call_aside
      File "c:\users\mario\appdata\local\programs\python\python36-32\lib\site-pa                         ckages\pkg_resources\__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "c:\users\mario\appdata\local\programs\python\python36-32\lib\site-pa                         ckages\pkg_resources\__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "c:\users\mario\appdata\local\programs\python\python36-32\lib\site-pa                         ckages\pkg_resources\__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "c:\users\mario\appdata\local\programs\python\python36-32\lib\site-pa                         ckages\pkg_resources\__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "c:\users\mario\appdata\local\programs\python\python36-32\lib\site-pa                         ckages\pkg_resources\__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "c:\users\mario\appdata\local\programs\python\python36-32\lib\site-pa                         ckages\pkg_resources\__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Mario\Ap                         pData\Local\Temp\pip-build-zad7g0os\sphinxcontrib-examplecode\

**Comment by aleixmorgadas** [comment]
I have checked using python2 and python3 and it worked using Linux machine. We also know it works on Mac machines, but never used Windows with Sphinx. It should be error Windows related, if you find the issue and could you post here the solution? Thank you.

I've already tried to find something in the [package repository](https://bitbucket.org/birkenfeld/sphinx-contrib/src/8e295053a27d/examplecode/?at=default) but no luck.

**Comment by quasarblue** [comment]
solved with
pip install --upgrade setuptools
