### ISSUE TITLE
error status

### ISSUE THREAD

**Issue by ags-21ct** [nemtech/nem2-docs#42]
nem2-cli monitor status
Monitoring SA6NUD-FS2DKX-VTGWFY-FGPVOK-JKCM6N-KBW4CD-JRUN using 
Error Error: Invalid URL: /ws
    at WebSocket.initAsClient (/usr/local/lib/node_modules/nem2-cli/node_modules/ws/lib/websocket.js:455:11)
    at new WebSocket (/usr/local/lib/node_modules/nem2-cli/node_modules/ws/lib/websocket.js:62:20)
    at Promise (/usr/local/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/Listener.js:77:38)
    at new Promise (<anonymous>)
    at Listener.open (/usr/local/lib/node_modules/nem2-cli/node_modules/nem2-sdk/dist/src/infrastructure/Listener.js:71:16)
    at default_1.execute (/usr/local/lib/node_modules/nem2-cli/build/src/commands/monitor/status.js:43:18)
    at CLI.executeCommand (/usr/local/lib/node_modules/nem2-cli/node_modules/clime/bld/core/cli.js:226:24)
    at CLI.<anonymous> (/usr/local/lib/node_modules/nem2-cli/node_modules/clime/bld/core/cli.js:80:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nem2-cli/node_modules/clime/bld/core/cli.js:4:58)

**Comment by dgarcia360** [comment]
It seems the profile does not have any node URL, or the node you are connecting is not responding.

1) Try to load the profile again. Edit localhost and your_private_key for your own parameters.

`$> nem2-cli profile create --privatekey your_private_key --network MIJIN_TEST --url http://localhost:3000
`
2) Make sure the node is working by opening this URL in your browser. Edit <url> with your node's url.

More info: https://nemtech.github.io/cli/overview.html
